---

  - name: Install a list of packages
    yum:
      name:
        - java-1.8.0-openjdk
        - wget
      state: present

  - name: Download Jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins Key
    command: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
             sudo amazon-linux-extras install epel -y 
             sudo yum update -y 

  - name: Install Jenkins packages
    yum:
      name:
        - jenkins
      state: present

  - name: Jenkins Service Start
    systemd:
      state: started
      name: jenkins
      enabled: yes
