---

- name: Set kernel parameters ipv4 forward
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'kernel.shmall', value: '3774873' }
    - { name: 'kernel.msgmax', value: '65535' }
    - { name: 'kernel.msgmnb', value: '65535' }

- name: Download mysql repo
  get_url:
    url: https://dev.mysql.com/get/{{ mysql_repo_rpm }}
    dest: /tmp/{{ mysql_repo_rpm }}
    mode: '0440'

- name: install mysql repo
  yum:
    name: /tmp/{{ mysql_repo_rpm }}
    state: present

- name: install mysql DB
  yum:
    name: mysql-community-server
    state: latest

- name: Make sure mysql service unit is running
  ansible.builtin.systemd:
    state: started
    name: mysqld
