---

- name: Install the latest version of Apache
  yum:
    name: "{{ http_name }}"
    state: latest

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /var/www/html/
    state: directory
    recurse: yes

- name: Template a file to /var/www/html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: raj.html
    dest: /var/www/html/raj.html

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: "{{ http_name }}"

