---

- name: Set kernel parameters ipv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Set kernel parameters ipv6.conf.all.disable
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present

- name: Set kernel parameters net.ipv6.conf.default.disable_ipv6
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    state: present

- name: install the latest version of Java
  yum:
    name: java
    state: latest
